apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: neptune-10ab
  name: neptune-10ab
  namespace: neptune
spec:
  replicas: 3                   # change
  selector:
    matchLabels:
      app: neptune-10ab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: neptune-10ab
    spec:
      serviceAccountName: neptune-sa-v2 # add
      containers:
        - image: httpd:2.4-alpine
          name: neptune-pod-10ab  # change
          resources:              # add
            limits:               # add
              memory: 50Mi        # add
            requests:             # add
              memory: 20Mi        # add
status: {}