apiVersion: v1
kind: Pod
metadata:
  labels:
    id: secret-handler
    uuid: 1428721e-8d1c-4c09-b5d6-afd79200c56a
    red_ident: 9cf7a7c0-fdb2-4c35-9c13-c2a0bb52b4a9
    type: automatic
  name: secret-handler
  namespace: moon
spec:
  volumes:
    - name: cache-volume1
      emptyDir: {}
    - name: cache-volume2
      emptyDir: {}
    - name: cache-volume3
      emptyDir: {}
    - name: secret2-volume              # add
      secret:                           # add
        secretName: secret2             # add
  containers:
    - name: secret-handler
      image: bash:5.0.11
      args: ['bash', '-c', 'sleep 2d']
      volumeMounts:
        - mountPath: /cache1
          name: cache-volume1
        - mountPath: /cache2
          name: cache-volume2
        - mountPath: /cache3
          name: cache-volume3
        - name: secret2-volume            # add
          mountPath: /tmp/secret2         # add
      env:
        - name: SECRET_KEY_1
          value: ">8$kH#kj..i8}HImQd{"
        - name: SECRET_KEY_2
          value: "IO=a4L/XkRdvN8jM=Y+"
        - name: SECRET_KEY_3
          value: "-7PA0_Z]>{pwa43r)__"
        - name: SECRET1_USER              # add
          valueFrom:                      # add
            secretKeyRef:                 # add
              name: secret1               # add
              key: user                   # add
        - name: SECRET1_PASS              # add
          valueFrom:                      # add
            secretKeyRef:                 # add
              name: secret1               # add
              key: pass                   # add